name: Multiarch builds
on:
  pull_request:
  push:

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    env:
      NIX_VERSION: 2.3.15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: ${{ startsWith(github.ref, 'refs/heads/master') }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Images
        uses: docker/build-push-action@v2
        with:
          build-args: |
            NIX_VERSION=${{ env.NIX_VERSION }}
          push: ${{ startsWith(github.ref, 'refs/heads/master') }}
          tags: nixos/nix:${{ env.NIX_VERSION }},nixos/nix:latest
